{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user{{ $attendee }}-metadata-mysql
  namespace: model-registries-ai501
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}