{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: user{{ $attendee}}-canopy
  labels:
    kubernetes.io/metadata.name: user{{ $attendee}}-canopy
    opendatahub.io/dashboard: 'true'
    modelmesh-enabled: 'false'
  annotations:
    openshift.io/description: 'user{{ $attendee}} Canopy Experiment Environment'
    openshift.io/display-name: user{{ $attendee}}-canopy
    openshift.io/requester: user{{ $attendee }}
spec:
  finalizers:
    - kubernetes
{{- end }}