{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canopy-workspace-pvc
  namespace: user{{ $attendee }}-toolings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
{{- end }}