{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user{{ $attendee }}-canopy
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# to edit/view monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user{{ $attendee }}-monitoring-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user{{ $attendee }}
---
# to view logs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user{{ $attendee }}-view-application-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-application-view
subjects:
- kind: User
  name: user{{ $attendee }}
  apiGroup: rbac.authorization.k8s.io
---
# for llama stack TODO: check if needed
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llama-stack-user{{ $attendee }}-role
  namespace: user{{ $attendee }}-canopy
rules:
- apiGroups:
  - "llamastack.io"
  resources:
  - llamastackdistributions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: llama-stack-user{{ $attendee }}-rolebinding
  namespace: user{{ $attendee }}-canopy
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llama-stack-user{{ $attendee }}-role
---
# for Guardrails Orchestrator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guardrailsorchestrators-user{{ $attendee }}-role
  namespace: user{{ $attendee }}-canopy
rules:
- apiGroups:
  - "trustyai.opendatahub.io"
  resources:
  - guardrailsorchestrators
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guardrailsorchestrators-user{{ $attendee }}-rolebinding
  namespace: user{{ $attendee }}-canopy
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guardrailsorchestrators-user{{ $attendee }}-role
# Make AI501 readonly for all users
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ai501-user{{ $attendee }}-rolebinding
  namespace: ai501
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-monitoring-view-user{{ $attendee }}
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
    resourceNames:
      - ai501
      - redhat-ods-monitoring
      - user{{ $attendee }}-test
      - user{{ $attendee }}-prod
      - user{{ $attendee }}-toolings
      - user{{ $attendee }}-canopy
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses/api
    resourceNames:
      - k8s
---
# Allow users to query metrics from ai501 namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user{{ $attendee }}-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view-user{{ $attendee }}
subjects:
- kind: User
  name: user{{ $attendee }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}