{{ $cluster_domain := .Values.cluster_domain }}
{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
apiVersion: v1
stringData:
  password: "thisisthepassword"
  username: "user{{ $attendee }}"
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  annotations:
    tekton.dev/git-0: https://gitea-gitea.{{ $cluster_domain }}
    sealedsecrets.bitnami.com/managed: "true"
  name: git-auth
  namespace: user{{ $attendee }}-toolings
{{- end }}