{{ $cluster_domain := .Values.cluster_domain }}
{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Secret
apiVersion: v1
metadata:
  name: genaiops-gitops-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/genaiops-gitops.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: backend-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/backend.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: evals-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/evals.git
  username: user{{ $attendee }}
type: Opaque
# ---
# kind: Secret
# apiVersion: v1
# metadata:
#   name: mcp-repo-secret
#   namespace: user{{ $attendee }}-toolings
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   password: thisisthepassword
#   type: git
#   url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/mcp.git
#   username: user{{ $attendee }}
# type: Opaque
{{- end }}
