{{ $cluster_domain := .Values.cluster_domain }}
{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Secret
apiVersion: v1
metadata:
  name: genaiops-gitops-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/genaiops-gitops.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: genaiops-helmcharts-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/genaiops-helmcharts.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: canopy-ui-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/canopy-ui.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: canopy-be-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/canopy-be.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: canopy-evals-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/canopy-evals.git
  username: user{{ $attendee }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: canopy-mcp-repo-secret
  namespace: user{{ $attendee }}-toolings
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  password: thisisthepassword
  type: git
  url: https://gitea-gitea.{{ $cluster_domain }}/user{{ $attendee }}/canopy-mcp.git
  username: user{{ $attendee }}
type: Opaque
{{- end }}
