{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: user{{ $attendee}}-toolings
  labels:
    kubernetes.io/metadata.name: user{{ $attendee}}-toolings
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: 'user{{ $attendee}} MLOps Toolings Project'
    openshift.io/display-name: user{{ $attendee}}-toolings
    openshift.io/requester: user{{ $attendee}}
spec:
  finalizers:
    - kubernetes
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
  namespace: user{{ $attendee }}-toolings
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user{{ $attendee }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: Namespace
apiVersion: v1
metadata:
  name: user{{ $attendee}}-test
  labels:
    kubernetes.io/metadata.name: user{{ $attendee}}-test
    opendatahub.io/dashboard: 'true'
    argocd.argoproj.io/managed-by: user{{ $attendee}}-toolings
    maistra.io/member-of: istio-system
    modelmesh-enabled: 'false'
  annotations:
    openshift.io/description: 'user{{ $attendee}} Test Project'
    openshift.io/display-name: user{{ $attendee}}-test
spec:
  finalizers:
    - kubernetes
---
kind: Namespace
apiVersion: v1
metadata:
  name: user{{ $attendee}}-prod
  labels:
    kubernetes.io/metadata.name: user{{ $attendee}}-prod
    opendatahub.io/dashboard: 'true'
    argocd.argoproj.io/managed-by: user{{ $attendee}}-toolings
    maistra.io/member-of: istio-system
    modelmesh-enabled: 'false'
  annotations:
    openshift.io/description: 'user{{ $attendee}} Prod Project'
    openshift.io/display-name: user{{ $attendee}}-prod
spec:
  finalizers:
    - kubernetes
{{- end }}