---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
spec:
  giteaImageTag: 1.20.0
  giteaVolumeSize: 4Gi
  giteaSsl: true
  postgresqlVolumeSize: 20Gi
  giteaAdminUser: opentlc-mgr
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPasswordSecretName: gitea-admin-password
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user%d"
  giteaUserNumber: {{ .Values.attendees }}
  giteaUserPasswordSecretName: gitea-user-password
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/rhoai-genaiops/canopy.git
    name: canopy
    private: true
  - repo: https://github.com/rhoai-genaiops/genaiops-gitops.git
    name: mlops-gitops
    private: true
  - repo: https://github.com/rhoai-genaiops/canopy-ui.git 
    name: canopy-ui
    private: true