---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
spec:
  giteaImageTag: 1.24.0
  giteaVolumeSize: 4Gi
  giteaSsl: true
  postgresqlVolumeSize: 20Gi
  giteaAdminUser: opentlc-mgr
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPasswordSecretName: gitea-admin-password
  giteaCreateUsers: true
  giteaUserNumber: {{ .Values.attendees }}
  {{- if eq (int .Values.attendees) 1 }}
  giteaGenerateUserFormat: "user1"
  {{- else}}
  giteaGenerateUserFormat: "user%d"
  {{- end }}
  giteaUserPasswordSecretName: gitea-user-password
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/rhoai-genaiops/canopy.git
    name: canopy
    private: true
  - repo: https://github.com/rhoai-genaiops/genaiops-gitops.git
    name: genaiops-gitops
    private: true
  - repo: https://github.com/rhoai-genaiops/canopy-ui.git 
    name: canopy-ui
    private: true
  - repo: https://github.com/rhoai-genaiops/canopy-be.git 
    name: canopy-be
    private: true
  - repo: https://github.com/rhoai-genaiops/genaiops-evals.git 
    name: genaiops-evals
    private: true