---
kind: Secret
apiVersion: v1
metadata:
  name: gitea-admin-password
  namespace: gitea
data:
  adminPassword: bXlQYXNzdzByZA==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: gitea-user-password
  namespace: gitea
data:
  userPassword: {{ $.Values.common_password | b64enc }}
type: Opaque
