---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: llama-32-fp8
    serving.kserve.io/deploymentMode: RawDeployment
  name: llama-32-fp8
  namespace: ai501
  labels:
    opendatahub.io/dashboard: 'true'
    monitoring.opendatahub.io/scrape: 'true'
    opendatahub.io/genai-asset: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 0
    model:
      args:
        - '--dtype=half'
        - '--max-model-len=20000' # to be adjusted to the max capacity of GPU used
        - '--gpu-memory-utilization=0.95'
        - '--max-num-seqs=64' # lowered from default 256 to avoid OOM during warmup
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=llama3_json'
        - '--chat-template=/opt/app-root/template/tool_chat_template_llama3.2_json.jinja'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 20Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: llama-32-fp8
      storageUri: 'oci://quay.io/rhoai-genaiops/llama32-3b-instruct-fp8:latest'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: g5
---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ''
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-display-name: vLLM
    opendatahub.io/template-name: vllm
    openshift.io/display-name: llama-32-fp8
  name: llama-32-fp8
  namespace: ai501
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name=llama32-fp8'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:ad756c01ec99a99cc7d93401c41b8d92ca96fb1ab7c5262919d818f2be4f3768'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llama32-fp8
  namespace: ai501
  labels:
    app: llama-32-fp8
spec:
  path: /
  to:
    kind: Service
    name: llama-32-fp8-predictor
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
