---
cluster_domain: apps.cluster-pwjcv.pwjcv.sandbox1619.opentlc.com
modelName: "llama32"
attendees: 10
common_password: thisisthepassword
minio:
  buckets:
    - name: pipeline
    - name: test-results
    - name: documents
