---
kind: KubernetesImagePuller
apiVersion: che.eclipse.org/v1alpha1
metadata:
  name: image-puller
  namespace: openshift-operators
spec:
  daemonsetName: k8s-image-puller
  images: 'code-server=quay.io/rhoai-genaiops/codeserver:0.9;llama-stack=quay.io/rhoai-genaiops/odh-llama-stack-core-rhel9:rhoai-3.4-shields;nemo=http://quay.io/rh-ee-mmisiura/nemo-guardrails:hf_classifier_fix_regex_checks;'