---
# PostgreSQL Database Credentials for Keycloak
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-pgsql-user
  namespace: keycloak
  labels:
    app: keycloak-pgsql
    component: database
type: Opaque
stringData:
  dbname: keycloak
  host: keycloak-pgsql.keycloak.svc
  port: "5432"
  user: keycloak
  password: {{ .Values.keycloak_pgsql_password | default "keycloakdbpass" | quote }}
