---
# Route for Keycloak external access
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
    component: auth
spec:
  host: sso.{{ .Values.cluster_domain }}
  to:
    kind: Service
    name: keycloak
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
