---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-oauth-secret
  namespace: sso
  labels:
    app: mcp-calendar
    component: oauth
  annotations:
    description: "OAuth client secret for MCP Calendar Server"
type: Opaque
stringData:
  client-secret: "thisisthepassword"

---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-test-user-secret
  namespace: sso
  labels:
    app: mcp-calendar
    component: oauth
  annotations:
    description: "Test user password for MCP Calendar OAuth realm"
type: Opaque
stringData:
  password: "thisisthepassword"
