---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-rhpds-gitea
  namespace: gitea-operator
spec:
  sourceType: grpc
  image: quay.io/rhpds/gitea-catalog:v2.1.0
  displayName: Red Hat Demo Platform (Gitea)
  publisher: Red Hat Demo Platform
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitea-operator
  namespace: gitea-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: redhat-rhpds-gitea
  sourceNamespace: gitea-operator
  startingCSV: gitea-operator.v2.1.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitea-operator
  namespace: gitea-operator
spec:
  targetNamespaces: []