---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "SSO project"
    openshift.io/display-name: "Red Hat SSO"
  name: sso
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
  name: sso
  namespace: sso
spec:
  targetNamespaces:
    - sso
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: sso
spec:
  channel: stable
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace