{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
# Allow lab-runner SA to manage resources in userX-canopy
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-runner-admin
  namespace: user{{ $attendee }}-canopy
subjects:
  - kind: ServiceAccount
    name: lab-runner
    namespace: ai501
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# Allow lab-runner SA to manage resources in userX-toolings
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-runner-admin
  namespace: user{{ $attendee }}-toolings
subjects:
  - kind: ServiceAccount
    name: lab-runner
    namespace: ai501
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# Allow lab-runner SA to manage resources in userX-test
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-runner-admin
  namespace: user{{ $attendee }}-test
subjects:
  - kind: ServiceAccount
    name: lab-runner
    namespace: ai501
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# Allow lab-runner SA to manage resources in userX-prod
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-runner-admin
  namespace: user{{ $attendee }}-prod
subjects:
  - kind: ServiceAccount
    name: lab-runner
    namespace: ai501
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}
