apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "canopy-board.fullname" . }}
  labels:
    {{- include "canopy-board.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
