---
apiVersion: v1
kind: Secret
metadata:
  name: prompt-tracker-secrets
  namespace: ai501
  labels:
    app: prompt-tracker
type: Opaque
stringData:
  git-password: "{{ .Values.common_password }}"
  s3-secret-key: "{{ .Values.common_password }}"
