apiVersion: v2
name: llama-stack-playground
description: A Helm chart for Llama Stack Playground UI
type: application
version: 1.0.3
appVersion: "latest"
maintainers:
  - name: ckavili
  - name: rhrolun
  - name: rcarrata