apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    alerting: {}
    managementState: Managed
    metrics:
      replicas: 1
      storage:
        retention: 90d
        size: 5Gi
    namespace: redhat-ods-monitoring
    traces:
      # Increased from 0.1 (10%) to 1.0 (100%) for development/testing
      # Recommended: Use 0.1 for production, 1.0 for dev/test environments
      # Note: Individual workloads can override via OTEL_TRACES_SAMPLER_ARG env var
      sampleRatio: '1.0'
      storage:
        backend: pv
        # Retention: 90 days (2160h)
        retention: 2160h0m0s
        # Storage size for Tempo traces
        size: 10Gi
  trustedCABundle:
    customCABundle: ''
    managementState: Managed
  # ServiceMesh configuration (optional, uncomment if using Service Mesh)
  # serviceMesh:
  #   managementState: Managed
  #   controlPlane:
  #     name: data-science-smcp
  #     namespace: istio-system
