# FROM registry.redhat.io/rhoai/odh-llama-stack-core-rhel9@sha256:86f8d82f589b4044ce9ac30cb62b4611951d2c383e669c8e2dc5bc74e69e6c86
# FROM quay.io/rhoai-genaiops/llama-stack-vllm-milvus-fms:rhoai-3.0
# FROM quay.io/opendatahub/llama-stack@sha256:0c6f763da98d4f729a830515974d64cf2116f2d095ca261a9af2c33a0e775505
FROM registry.redhat.io/rhoai/odh-llama-stack-core-rhel9@sha256:13ec5c9b96a9ca8c0a1fcc0568cf6f893478742d28d3b1381f073b9bdafb3320

RUN mkdir -p /opt/app-root/src/.llama/distributions/vllm \
&& chgrp -R 0 /opt/app-root/src \
&& chmod -R g=u /opt/app-root/src \
&& sed -i '/provider_vector_db_id = extra_body.get("provider_vector_db_id")/a\        vector_db_id = extra_body.get("vector_db_id")' \
    /opt/app-root/lib/python3.12/site-packages/llama_stack/providers/utils/memory/openai_vector_store_mixin.py \
&& sed -i 's/vector_db_id = provider_vector_db_id or generate_object_id/vector_db_id = vector_db_id or provider_vector_db_id or generate_object_id/' \
    /opt/app-root/lib/python3.12/site-packages/llama_stack/providers/utils/memory/openai_vector_store_mixin.py \
&& sed -i '/extra = params.model_extra or {}/a\        vector_db_id = extra.get("vector_db_id")' \
    /opt/app-root/lib/python3.12/site-packages/llama_stack/core/routers/vector_io.py \
&& sed -i 's/vector_db_id = f"vs_{uuid.uuid4()}"/vector_db_id = vector_db_id or f"vs_{uuid.uuid4()}"/' \
    /opt/app-root/lib/python3.12/site-packages/llama_stack/core/routers/vector_io.py