---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prompt-injection-model-pvc
  labels:
    app: guardrails-multi-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-hap-model-pvc
  labels:
    app: guardrails-multi-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: language-detector-model-pvc
  labels:
    app: guardrails-multi-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
