{{ $attendees := (.Values.attendees | int) }}
{{- range $attendee := until $attendees }}
---
kind: Secret
apiVersion: v1
metadata:
  name: feast
  namespace: user{{ $attendee }}-jukebox
  labels:
    app: feature-store
stringData:
  database-name: feast
  database-password: feast
  database-user: feast
type: Opaque
{{- end }}